// Generated by https://quicktype.io

export interface Calendar {
    code:   number;
    status: string;
    events: Calendary[];
}

export interface Calendary {
    id:         number;
    title:      string;
    description:string;
    path:       string;
    brand:      string;
    type:       string;
    status:     string;
    event_date: string;
    detail:     string;
    created_at: string;
    updated_at: string;
    event_images: EventImage[];
}

export interface EventImage {
    id:         number;
    path:       string;
    event_id:   number;
    created_at: Date;
    updated_at: Date;
}

export interface ImageEventOrder {
    id:            number;
    image:         string;
    title:         string;
    description:   string;
    dateEvent:     string;
    event_images: EventImage[];
 }